version: "3.7"
services:
  app:
    build: ../
    # command: "/bin/sh -c 'poetry run ./manage.py runserver 0.0.0.0:8000 --nostatic'"
    tty: true
    environment:
      - USER=$USER
      - PYTHONPATH=/workspace
      - MYPYPATH=out
    volumes:
      - ..:/workspace:cached
      - /workspace/__pycache__/
      - /workspace/.mypy_cache/
      - /workspace/.pytest_cache/
    ports:
      - "8000:8000"